import type { ComponentType } from "react";
import {
  Activity,
  AlarmClock,
  Apple,
  Bed,
  Bell,
  Bike,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Calendar,
  Camera,
  Carrot,
  Check,
  CheckCircle,
  Clock,
  Code,
  Coffee,
  Droplet,
  Dumbbell,
  Flame,
  Flower,
  Footprints,
  Gamepad2,
  GraduationCap,
  Guitar,
  Hash,
  Heart,
  HeartPulse,
  Languages,
  Leaf,
  Moon,
  Mountain,
  Music,
  Paintbrush,
  PenLine,
  PiggyBank,
  Pill,
  Recycle,
  Smartphone,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Tag,
  Target,
  Trophy,
  Utensils,
  Wallet,
  type LucideProps,
} from "lucide-react";

export interface HabitIconDef {
  name: string;
  Icon: ComponentType<LucideProps>;
}

// The curated, selectable icon set. Importing named icons (not `import *`)
// keeps Lucide tree-shakeable — only these ship, not the full ~1500-icon set.
export const HABIT_ICONS: HabitIconDef[] = [
  { name: "check", Icon: Check },
  { name: "check-circle", Icon: CheckCircle },
  { name: "target", Icon: Target },
  { name: "flame", Icon: Flame },
  { name: "trophy", Icon: Trophy },
  { name: "star", Icon: Star },
  { name: "sparkles", Icon: Sparkles },
  { name: "heart", Icon: Heart },
  { name: "book-open", Icon: BookOpen },
  { name: "book", Icon: Book },
  { name: "pen-line", Icon: PenLine },
  { name: "graduation-cap", Icon: GraduationCap },
  { name: "languages", Icon: Languages },
  { name: "code", Icon: Code },
  { name: "briefcase", Icon: Briefcase },
  { name: "droplet", Icon: Droplet },
  { name: "coffee", Icon: Coffee },
  { name: "apple", Icon: Apple },
  { name: "carrot", Icon: Carrot },
  { name: "utensils", Icon: Utensils },
  { name: "pill", Icon: Pill },
  { name: "dumbbell", Icon: Dumbbell },
  { name: "footprints", Icon: Footprints },
  { name: "bike", Icon: Bike },
  { name: "activity", Icon: Activity },
  { name: "heart-pulse", Icon: HeartPulse },
  { name: "mountain", Icon: Mountain },
  { name: "moon", Icon: Moon },
  { name: "bed", Icon: Bed },
  { name: "sunrise", Icon: Sunrise },
  { name: "sun", Icon: Sun },
  { name: "alarm-clock", Icon: AlarmClock },
  { name: "flower", Icon: Flower },
  { name: "brain", Icon: Brain },
  { name: "smile", Icon: Smile },
  { name: "music", Icon: Music },
  { name: "guitar", Icon: Guitar },
  { name: "paintbrush", Icon: Paintbrush },
  { name: "camera", Icon: Camera },
  { name: "wallet", Icon: Wallet },
  { name: "piggy-bank", Icon: PiggyBank },
  { name: "sprout", Icon: Sprout },
  { name: "leaf", Icon: Leaf },
  { name: "recycle", Icon: Recycle },
  { name: "smartphone", Icon: Smartphone },
  { name: "gamepad-2", Icon: Gamepad2 },
  { name: "bell", Icon: Bell },
  { name: "calendar", Icon: Calendar },
  { name: "clock", Icon: Clock },
  { name: "hash", Icon: Hash },
  { name: "tag", Icon: Tag },
];

export const HABIT_ICON_MAP: Record<string, ComponentType<LucideProps>> =
  Object.fromEntries(HABIT_ICONS.map((i) => [i.name, i.Icon]));
